/**
 * The bridge between the contract package and the OpenAPI document.
 *
 * `@odyssey/types` exports plain zod schemas with no knowledge of HTTP or OpenAPI.
 * This module is the single place that gives them component names, so the emitted
 * document contains `#/components/schemas/MenuItem` rather than the same shape inlined
 * at a dozen call sites — which is also what makes Orval generate one shared
 * `MenuItem` type instead of a dozen anonymous duplicates.
 *
 * IMPORTANT: `extendZodWithOpenApi(z)` must run before any `.openapi()` call. It is
 * invoked here, and every route module imports its schemas from this file, so the
 * ordering is structural rather than something a future edit can accidentally break.
 */
import { extendZodWithOpenApi } from '@hono/zod-openapi'
import { z } from 'zod'

import {
  apiErrorSchema,
  createCustomerRequestSchema,
  createMenuCategoryRequestSchema,
  createMenuItemRequestSchema,
  createOrderRequestSchema,
  customerSchema,
  customerWithStatsSchema,
  dashboardOverviewSchema,
  menuCategorySchema,
  menuCategoryWithItemsSchema,
  menuItemSchema,
  menuItemWithCategorySchema,
  orderDetailSchema,
  orderItemSchema,
  orderSummarySchema,
  paginationMetaSchema,
  restaurantSettingsSchema,
  transitionOrderRequestSchema,
  updateCustomerRequestSchema,
  updateMenuCategoryRequestSchema,
  updateMenuItemRequestSchema,
  updateSettingsRequestSchema,
} from '@odyssey/types'

// Importing `@hono/zod-openapi` already applies this to the shared zod instance — it
// calls `extendZodWithOpenApi(zodModule.z)` at its own module scope. The explicit call is
// kept because it documents the dependency and is idempotent.
extendZodWithOpenApi(z)

/**
 * Attach an OpenAPI component name to a contract schema.
 *
 * Why this is a helper rather than a bare `schema.openapi(name)` call:
 *
 * `.openapi()` is added to zod's prototype by `@hono/zod-openapi` when it is imported.
 * That works wherever a single zod module instance exists — the Worker runtime, `tsx`,
 * and the `emit-openapi` script that actually produces the committed document. Vitest,
 * however, builds its own module graph and can hand the test process a zod whose
 * prototype was never patched (the patch is idempotent-guarded, so re-applying it does
 * not help). Importing this module would then throw at load time and every test would
 * fail before running.
 *
 * Component *names* are presentation metadata for the generated document; they do not
 * affect validation, routing, or any behaviour under test. So when the extension is
 * absent the schema is passed through unnamed rather than crashing.
 *
 * The document that ships is generated by `pnpm gen:contract` under `tsx`, where the
 * extension is present and every component is properly named — verified by inspecting
 * `services/backend/openapi.json`, which contains named `#/components/schemas/*` entries.
 */
function named<T>(schema: T, name: string): T {
  const candidate = schema as { openapi?: (componentName: string) => T }
  return typeof candidate.openapi === 'function' ? candidate.openapi(name) : schema
}

/* --------------------------------- Shared --------------------------------- */

export const ApiErrorSchema = named(apiErrorSchema, 'ApiError')
export const PaginationMetaSchema = named(paginationMetaSchema, 'PaginationMeta')

/**
 * Wrap an item schema in the list envelope and register it under a stable name.
 * Naming each concrete instantiation is what stops Orval emitting
 * `PaginatedOrderSummary200`-style noise.
 */
export function registerPaginated<T extends z.ZodType>(item: T, name: string) {
  return named(
    z.object({
      data: z.array(item),
      pagination: PaginationMetaSchema,
    }),
    name,
  )
}

/* ---------------------------------- Menu ---------------------------------- */

export const MenuCategorySchema = named(menuCategorySchema, 'MenuCategory')
export const MenuItemSchema = named(menuItemSchema, 'MenuItem')
export const MenuItemWithCategorySchema = named(menuItemWithCategorySchema, 'MenuItemWithCategory')
export const MenuCategoryWithItemsSchema =
  named(menuCategoryWithItemsSchema, 'MenuCategoryWithItems')
export const CreateMenuCategoryRequestSchema = named(
  createMenuCategoryRequestSchema,
  'CreateMenuCategoryRequest',
)
export const UpdateMenuCategoryRequestSchema = named(
  updateMenuCategoryRequestSchema,
  'UpdateMenuCategoryRequest',
)
export const CreateMenuItemRequestSchema =
  named(createMenuItemRequestSchema, 'CreateMenuItemRequest')
export const UpdateMenuItemRequestSchema =
  named(updateMenuItemRequestSchema, 'UpdateMenuItemRequest')

/* -------------------------------- Customers -------------------------------- */

export const CustomerSchema = named(customerSchema, 'Customer')
export const CustomerWithStatsSchema = named(customerWithStatsSchema, 'CustomerWithStats')
export const CreateCustomerRequestSchema =
  named(createCustomerRequestSchema, 'CreateCustomerRequest')
export const UpdateCustomerRequestSchema =
  named(updateCustomerRequestSchema, 'UpdateCustomerRequest')

/* ---------------------------------- Orders --------------------------------- */

export const OrderItemSchema = named(orderItemSchema, 'OrderItem')
export const OrderSummarySchema = named(orderSummarySchema, 'OrderSummary')
export const OrderDetailSchema = named(orderDetailSchema, 'OrderDetail')
export const CreateOrderRequestSchema = named(createOrderRequestSchema, 'CreateOrderRequest')
export const TransitionOrderRequestSchema = named(
  transitionOrderRequestSchema,
  'TransitionOrderRequest',
)

/* --------------------------------- Settings -------------------------------- */

export const RestaurantSettingsSchema = named(restaurantSettingsSchema, 'RestaurantSettings')
export const UpdateSettingsRequestSchema =
  named(updateSettingsRequestSchema, 'UpdateSettingsRequest')

/* ---------------------------------- Stats ---------------------------------- */

export const DashboardOverviewSchema = named(dashboardOverviewSchema, 'DashboardOverview')

export { z }
