/**
 * Applies pending SQL migrations from `./drizzle`.
 *
 * Uses the real migration files generated by `drizzle-kit generate` rather than
 * `drizzle-kit push`. Push diffs the schema straight onto the database, which is
 * convenient in a sandbox but has no reviewable artifact and no ordering guarantees —
 * committed migrations mean the exact DDL that will run is visible in the diff.
 *
 * Run with:  pnpm db:migrate
 */
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { config } from 'dotenv'
import { drizzle } from 'drizzle-orm/postgres-js'
import { migrate } from 'drizzle-orm/postgres-js/migrator'
import postgres from 'postgres'

config({ path: '../../.env', quiet: true })

const databaseUrl = process.env.DATABASE_URL

if (!databaseUrl) {
  console.error(
    'DATABASE_URL is not set.\n\n' +
      'Copy the example env file at the repo root:\n' +
      '  cp .env.example .env\n',
  )
  process.exit(1)
}

const migrationsFolder = resolve(dirname(fileURLToPath(import.meta.url)), '../drizzle')

// `max: 1` is required: migrations must run sequentially on a single connection.
const client = postgres(databaseUrl, { max: 1 })

try {
  console.log('Applying migrations...')
  await migrate(drizzle(client), { migrationsFolder })
  console.log('Migrations applied.')
} catch (error) {
  console.error('\nMigration failed:', error instanceof Error ? error.message : error)
  console.error(
    '\nIs Postgres running? Start it with:\n' +
      '  docker compose up -d\n',
  )
  process.exit(1)
} finally {
  await client.end()
}
